security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            id: App\Auth\Infrastructure\Persistence\DoctrineUserRepository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/login
            stateless: true
            json_login:
                check_path: /api/v1/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/v1/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/stations, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/stats, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/routes, roles: ROLE_API }
        - { path: ^/api/v1/me, roles: ROLE_API }
        - { path: ^/api, roles: ROLE_API }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext

        firewalls:
            api:
                pattern: ^/api
                stateless: true
                security: false
